spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Test-DB
    username: tripgether
    password: 1222
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: 127.0.0.1  # Redis 서버 주소 (예: localhost, Redis 서버 IP 등)
      port: 6379       # Redis 포트 (기본값 6379)
      #password: your_password  # 비밀번호가 있다면 여기에 입력

logging:
  level:
    root: INFO
    com.tripgether: DEBUG
    p6spy: INFO