spring:
    application:
        name: tripgether-be
    profiles:
        active: dev

# 서버 설정
server:
    port: 8080
    servlet:
        context-path: /

# 로깅 설정
logging:
    level:
        com.tripgether.be: INFO
        org.springframework.web: DEBUG

